### PR TITLE
Fix EZP-24763: Concurrency problems in generating image aliases

### PR DESCRIPTION
**Pull request by yannickroger**
Link: https://jira.ez.no/browse/EZP-24763

## Description
This is a an adaptation of #24 for master. I fixed a couple of conflict. I separated the fix for the issue from the code improvement.

It seems that git gave me the paternity of the first fix while tweaking it (damn it).

## Test
None. I only did some git work on it. I don't have an oracle setup. So you better trust @gggeek and check that I didn't mess anything up.

### CODE REVIEW

**Comment by yannickroger** [comment]
ping @gggeek @andrerom @bdunogier

**Comment by gggeek** [comment]
If you're in no hurry, I'll give it at least one try, most likely over the weekend.
Q: is master supposed to work with ezp 5.3 or 5.4 ?

**Comment by andrerom** [comment]
+1

> 5.3 or 5.4

Neither, you never finished your pr's.

**Comment by gggeek** [comment]
ha! So 5.?

**Comment by andrerom** [comment]
Pi

**Comment by yannickroger** [comment]
After talking to @andrerom we are merging this for now, so our QA can start working on it. If you have time to try it out @gggeek you can add feedback on the PR.

**Pull request merged**
